// Code generated by MockGen. DO NOT EDIT.
// Source: get_rows.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRowsGetter is a mock of RowsGetter interface.
type MockRowsGetter struct {
	ctrl     *gomock.Controller
	recorder *MockRowsGetterMockRecorder
}

// MockRowsGetterMockRecorder is the mock recorder for MockRowsGetter.
type MockRowsGetterMockRecorder struct {
	mock *MockRowsGetter
}

// NewMockRowsGetter creates a new mock instance.
func NewMockRowsGetter(ctrl *gomock.Controller) *MockRowsGetter {
	mock := &MockRowsGetter{ctrl: ctrl}
	mock.recorder = &MockRowsGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRowsGetter) EXPECT() *MockRowsGetterMockRecorder {
	return m.recorder
}

// GetRows mocks base method.
func (m *MockRowsGetter) GetRows() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRows")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetRows indicates an expected call of GetRows.
func (mr *MockRowsGetterMockRecorder) GetRows() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRows", reflect.TypeOf((*MockRowsGetter)(nil).GetRows))
}
